apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: c8r6722dd-python
  janus-idp.io/tekton: c8r6722dd-python
  backstage.io/kubernetes-id: c8r6722dd-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: c8r6722dd-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
